from tkinter import*
root=Tk()

#Label(text=":").grid(row=0,column=0)
#table_name=Entry(width=30)
#table_name.grid(row=0,column=1,columnspan=3)

#Label(text="TEISIPÄEV:").grid(row=0,column=0)
#table_name=Entry(width=30)
#table_name.grid(row=0,column=1,columnspan=3)

#Label(text="KOLMAPÄEV:").grid(row=0,column=0)
#table_name=Entry(width=30)
#table_name.grid(row=0,column=1,columnspan=3)

#Label(text="NELJAPÄEV:").grid(row=0,column=0)
#table_name=Entry(width=30)
#table_name.grid(row=0,column=1,columnspan=3)

#Label(text="REEDE:").grid(row=0,column=0)
#table_name=Entry(width=30)
#table_name.grid(row=0,column=1,columnspan=3)

#Label(text="столбцов: ").grid(row=1,column=0)
#table_column=Spinbox(width=7,from_=1,to=50)
#table_column.grid(row=1,column=1)
#Label(text="столбцов:").grid(row=1,column=2)
#table_row=Spinbox(width=7,from_=1,to=100)
#table_row.grid(row=1,column=3)

#Button(text="справка").grid(row=2,column=0)
#Button(text="вставить").grid(row=2,column=2)
#Button(text="отменить").grid(row=2,column=3)


#Label(text="").grid(row=2, column=0)

#Label(text="Пн").grid(row=0, column=0)
#Label(text="").grid(row=2, column=1)
#Button(text="доп.эстонский").grid(row=1, column=1)
#Button(text="логистика").grid(row=0, column=2)
#Button(text="логистика").grid(row=1, column=2)
#Button(text="матан").grid(row=0, column=3)
#Button(text="матан").grid(row=1, column=3)
#Button(text="окно").grid(row=0, column=4)
#Button(text="окно").grid(row=1, column=4)
#Button(text="Keel ja \nkirjandus").grid(row=0, column=4)
#Button(text="Keel ja \nkirjandus").grid(row=1, column=4)
#Button(text="Tugiõpe \n(matemaatika)").grid(row=0, column=4)
#Button(text="Tugiõpe \n(matemaatika)").grid(row=1, column=4)

#Label(text="Вт").grid(row=2, column=0)
#Label(text="").grid(row=3, column=0)
#Button(text="доп.химия").grid(row=2, column=1)
#Button(text="Tugiõpe \n(keemia)").grid(row=3, column=1)
#Button(text="программирование").grid(row=2, column=2)
#Button(text="программирование").grid(row=3, column=2)
#Button(text="окно").grid(row=2, column=3)
#Button(text="окно").grid(row=3, column=3)
#Button(text="физика").grid(row=2, column=4)
#Button(text="физика").grid(row=3, column=4)

#Label(text="Ср").grid(row=4, column=0)
#Label(text="").grid(row=5, column=0)
#Button(text="доп.эст").grid(row=4, column=1)
#Button(text="искусство").grid(row=4, column=2)
#Button(text="искусство").grid(row=5, column=2)
#Button(text="окно").grid(row=4, column=3)
#Button(text="окно").grid(row=5, column=3)
#Button(text="физра").grid(row=4, column=4)
#Button(text="физра").grid(row=5, column=4)

#Label(text="Чт").grid(row=6, column=0)
#Label(text="").grid(row=7, column=0)
#Button(text="логистика").grid(row=6, column=1)
#Button(text="логистика").grid(row=7, column=1)
#Button(text="окно").grid(row=6, column=2)
#Button(text="окно").grid(row=7, column=2)
#Button(text="программирование").grid(row=6, column=3)
#Button(text="программирование").grid(row=7, column=3)
#Button(text="Inglise \nkeel").grid(row=6, column=4)
#Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=7, column=4)
#Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=6, column=5)
#Button(text="эстонский").grid(row=7, column=5)

#Label(text="Пт").grid(row=8, column=0)
#Label(text="").grid(row=9, column=0)
#Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=9, column=1)
#Button(text="Eesti \nkeel").grid(row=8, column=1)
#Button(text="программирование").grid(row=8, column=2)
#Button(text="программирование").grid(row=9, column=2)
#Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=8, column=3)
#Button(text="английский").grid(row=9, column=3)

Label(text=" ").grid(row=0,column=0)
Label(text="0\n7.40-8.25",borderwidth=1,relief="solid").grid(row=0,column=2,sticky=W+E+N+S)
Label(text="1\n8.30-9.15",borderwidth=1,relief="solid").grid(row=0,column=3,sticky=W+E+N+S)
Label(text="2\n9.20-10.05",borderwidth=1,relief="solid").grid(row=0,column=4,sticky=W+E+N+S)
Label(text="3\n10.10-10.55",borderwidth=1,relief="solid").grid(row=0,column=5,sticky=W+E+N+S)
Label(text="4\n11.00-11.45",borderwidth=1,relief="solid").grid(row=0,column=6,sticky=W+E+N+S)
Label(text="5\n11.50-12.35",borderwidth=1,relief="solid").grid(row=0,column=7,sticky=W+E+N+S)
Label(text="6\n12.40-13.25",borderwidth=1,relief="solid").grid(row=0,column=8,sticky=W+E+N+S)
Label(text="7\n13.30-14.15",borderwidth=1,relief="solid").grid(row=0,column=9,sticky=W+E+N+S)
Label(text="8\n14.20-15.05",borderwidth=1,relief="solid").grid(row=0,column=10,sticky=W+E+N+S)
Label(text="9\n15.10-15.55",borderwidth=1,relief="solid").grid(row=0,column=11,sticky=W+E+N+S)
Label(text="10\n16.00-16.45",borderwidth=1,relief="solid").grid(row=0,column=12,sticky=W+E+N+S)

pn=Label(text="пн",borderwidth=1,relief="raised").grid(row=1,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
vt=Label(text="вт",borderwidth=1,relief="raised").grid(row=3,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
sr=Label(text="ср",borderwidth=1,relief="raised").grid(row=5,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
ct=Label(text="чт",borderwidth=1,relief="raised").grid(row=7,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
pt=Label(text="пт",borderwidth=1,relief="raised").grid(row=9,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)

Label(text=" ",borderwidth=1,relief="solid").grid(row=1,column=3,sticky=W+E+N+S)
esttug2=Button(text="доп.эстонский \n 1 группа",bg="#ff0086",borderwidth=1,relief="flat").grid(row=2,column=3,sticky=W+E+N+S)
esmLogist=Button(text="логистика",bg="#ffb1da",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=4,columnspan=2,sticky=W+E+N+S)
mat=Button(text="Matemaatika",bg="#bc0063",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=6,columnspan=2,sticky=W+E+N+S)
Label(text=" Перерыв ",bg="#730086",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=8,sticky=W+E+N+S)
keel=Button(text="Keel ja kirjandus",bg="#32F224",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=9,columnspan=2,sticky=W+E+N+S)
tugmat=Button(text="Tugiõpe \n Matemaatika",bg="#bc0063",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=11,sticky=W+E+N+S)

Label(text=" ",borderwidth=1,relief="flat").grid(row=6,column=3,sticky=W+E+N+S)
tugkeem=Button(text="Tugiõpe Keemia",borderwidth=1,relief="flat",bg="#C929CB").grid(row=3,rowspan=2,column=3,sticky=W+E+N+S)
teisprog=Button(text="Programmeerimise alused \n (eesti keeles)",bg="lightblue",borderwidth=1,relief="flat").grid(row=3,rowspan=2,column=4,columnspan=3,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=7,sticky=W+E+N+S)
fuusika=Button(text="Füüsika",bg="pink",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=8,columnspan=2,sticky=W+E+N+S)

esttug1=Button(text="Tugiõpe Eesti keel \n 2 grupp",borderwidth=1,relief="flat",bg="#ff0086").grid(row=5,column=3,sticky=W+E+N+S)
kunst=Button(text="Kunstiained",borderwidth=1,relief="flat",bg="#C929CB").grid(row=5,rowspan=2,column=4,columnspan=2,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="flat").grid(row=5,rowspan=2,column=6,sticky=W+E+N+S)
kehalinekasv=Button(text="Kehaline Kasvatus",borderwidth=1,relief="flat",bg="#C929CB").grid(row=5,rowspan=2,column=7,columnspan=2,sticky=W+E+N+S)

neljLogist=Button(text="Logistikateenused ja \n varude juhtmine",borderwidth=1,relief="solid",bg="#ffb1da").grid(row=7,rowspan=2,column=3,columnspan=2,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=5,sticky=W+E+N+S)
neljprog=Button(text="Programmeerimise alused \n (eesti keeles)",bg="lightblue",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=6,columnspan=2,sticky=W+E+N+S)
ingl1=Button(text="Inglise keel",borderwidth=1,relief="solid",bg="#E0E4C0").grid(row=7,column=8,columnspan=2,sticky=W+E+N+S)
merk2=Button(text="Rakendustarkvara ja \n arenduskeskkonna loomine \n (IT valdkonna alusteadmised)",borderwidth=1,relief="solid",bg="#CF4141").grid(row=8,column=8,columnspan=2,sticky=W+E+N+S)
merk1=Button(text="Rakendustarkvara ja \n arenduskeskkonna loomine \n (IT valdkonna alusteadmised)",borderwidth=1,relief="solid",bg="#CF4141").grid(row=7,column=10,columnspan=2,sticky=W+E+N+S)
est2=Button(text="Eesti keel \n 2 grupp",borderwidth=1,relief="solid",bg="#9d7a73").grid(row=8,column=10,columnspan=2,sticky=W+E+N+S)
ruhm=Button(text="Rühmajuhataja \n tund",borderwidth=1,relief="solid",bg="#F335F6").grid(row=7,rowspan=2,column=12,sticky=W+E+N+S)

est1=Button(text="Eesti keel \n 1 grupp",borderwidth=1,relief="solid",bg="#F335F6").grid(row=9,column=3,columnspan=2,sticky=W+E+N+S)
merkul2=Button(text="Rakendustarkvara ja \n arenduskeskkonna loomine \n (IT valdkonna alusteadmised)",borderwidth=1,relief="solid",bg="#CF4141").grid(row=10,column=3,columnspan=2,sticky=W+E+N+S)
redprogram=Button(text="Programmeerimise alused \n (eesti keeles)",bg="lightblue",borderwidth=1,relief="solid").grid(row=9,rowspan=2,column=5,columnspan=5,sticky=W+E+N+S)
merkul1=Button(text="Rakendustarkvara ja \n arenduskeskkonna loomine \n (IT valdkonna alusteadmised)",borderwidth=1,relief="solid",bg="#CF4141").grid(row=9,column=10,columnspan=2,sticky=W+E+N+S)
ingl2=Button(text="inglise keel",borderwidth=1,relief="solid",bg="#32F224").grid(row=10,column=10,columnspan=2,sticky=W+E+N+S)


root.mainloop()