from tkinter import*
root=Tk()
root.configure(bg="#c2abff")

#Label(text=" ").grid(row=0,column=0)
Label(text="0\n7.40-8.25",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=2,sticky=W+E+N+S)
Label(text="1\n8.30-9.15",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=3,sticky=W+E+N+S)
Label(text="2\n9.20-10.05",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=4,sticky=W+E+N+S)
Label(text="3\n10.10-10.55",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=5,sticky=W+E+N+S)
Label(text="4\n11.00-11.45",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=6,sticky=W+E+N+S)
Label(text="5\n11.50-12.35",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=7,sticky=W+E+N+S)
Label(text="6\n12.40-13.25",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=8,sticky=W+E+N+S)
Label(text="7\n13.30-14.15",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=9,sticky=W+E+N+S)
Label(text="8\n14.20-15.05",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=10,sticky=W+E+N+S)
Label(text="9\n15.10-15.55",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=11,sticky=W+E+N+S)
Label(text="10\n16.00-16.45",bg="#c2abff",borderwidth=1,relief="groove").grid(row=0,column=12,sticky=W+E+N+S)

pn=Label(text="пн",bg="#730086",borderwidth=1,relief="groove").grid(row=1,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
vt=Label(text="вт",bg="#730086",borderwidth=1,relief="groove").grid(row=3,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
sr=Label(text="ср",bg="#730086",borderwidth=1,relief="groove").grid(row=5,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
ct=Label(text="чт",bg="#730086",borderwidth=1,relief="groove").grid(row=7,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
pt=Label(text="пт",bg="#730086",borderwidth=1,relief="groove").grid(row=9,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)

Label(text=" ",bg="#c2abff",borderwidth=1,relief="groove").grid(row=1,column=3,sticky=W+E+N+S)
dope2=Button(text="доп.эстонский \n 2 группа",bg="#ff0086",borderwidth=1,relief="flat").grid(row=2,column=3,sticky=W+E+N+S)
log=Button(text="логистика",bg="#ffb1da",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=4,columnspan=2,sticky=W+E+N+S)
mat=Button(text="математика",bg="#fd41bd",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=6,columnspan=2,sticky=W+E+N+S)
Label(text="окно",bg="#730086",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=8,sticky=W+E+N+S)
ru=Button(text="русский язык",bg="#FF35A0",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=9,columnspan=2,sticky=W+E+N+S)
dopm=Button(text="доп.математика",bg="#fd41bd",borderwidth=1,relief="flat").grid(row=1,rowspan=2,column=11,sticky=W+E+N+S)

Label(text=" ",bg="#c2abff",borderwidth=1,relief="groove").grid(row=6,column=3,sticky=W+E+N+S)
doph=Button(text="доп.химия",borderwidth=1,relief="flat",bg="#C929CB").grid(row=3,rowspan=2,column=3,sticky=W+E+N+S)
py1=Button(text="программирование",bg="#c57eff",borderwidth=1,relief="flat").grid(row=3,rowspan=2,column=4,columnspan=3,sticky=W+E+N+S)
Label(text="окно",bg="#730086",borderwidth=1,relief="flat").grid(row=3,rowspan=2,column=7,sticky=W+E+N+S)
sc=Button(text="физика",bg="#9a76fa",borderwidth=1,relief="flat").grid(row=3,rowspan=2,column=8,columnspan=2,sticky=W+E+N+S)

dope=Button(text="доп.эстонский \n 1 группа",borderwidth=1,relief="flat",bg="#ff0086").grid(row=5,column=3,sticky=W+E+N+S)
izo=Button(text="искусство",borderwidth=1,relief="flat",bg="#C929CB").grid(row=5,rowspan=2,column=4,columnspan=2,sticky=W+E+N+S)
Label(text="окно",bg="#730086",borderwidth=1,relief="flat").grid(row=5,rowspan=2,column=6,sticky=W+E+N+S)
pe=Button(text="физкультура",borderwidth=1,relief="flat",bg="#C929CB").grid(row=5,rowspan=2,column=7,columnspan=2,sticky=W+E+N+S)

log2=Button(text="логистика",borderwidth=1,relief="flat",bg="#ffb1da").grid(row=7,rowspan=2,column=3,columnspan=2,sticky=W+E+N+S)
Label(text="окно",bg="#730086",borderwidth=1,relief="flat").grid(row=7,rowspan=2,column=5,sticky=W+E+N+S)
py2=Button(text="программирование",bg="#c57eff",borderwidth=1,relief="flat").grid(row=7,rowspan=2,column=6,columnspan=2,sticky=W+E+N+S)
en1=Button(text="английский \n 1 группа",bg="#c7b5f7",borderwidth=1,relief="flat").grid(row=7,column=8,columnspan=2,sticky=W+E+N+S)
exl2=Button(text="офисные программы \n 2 группа",borderwidth=1,relief="flat",bg="#FF71BC").grid(row=8,column=8,columnspan=2,sticky=W+E+N+S)
exl1=Button(text="офисные программы \n 1 группа",borderwidth=1,relief="flat",bg="#FF71BC").grid(row=7,column=10,columnspan=2,sticky=W+E+N+S)
est2=Button(text="эстонский \n 2 группа",bg="#ff0086",borderwidth=1,relief="flat").grid(row=8,column=10,columnspan=2,sticky=W+E+N+S)

et1=Button(text="эстонский \n 1 группа",bg="#ff0086",borderwidth=1,relief="flat").grid(row=9,column=3,columnspan=2,sticky=W+E+N+S)
exl22=Button(text="офисные программы \n 2 группа",borderwidth=1,bg="#FF71BC",relief="flat").grid(row=10,column=3,columnspan=2,sticky=W+E+N+S)
py3=Button(text="программирование",bg="#c57eff",borderwidth=1,relief="flat").grid(row=9,rowspan=2,column=5,columnspan=5,sticky=W+E+N+S)
exl11=Button(text="офисные программы \n 1 группа",borderwidth=1,bg="#FF71BC",relief="flat").grid(row=9,column=10,columnspan=2,sticky=W+E+N+S)
eng2=Button(text="английский \n 2 группа",borderwidth=1,bg="#c7b5f7",relief="flat").grid(row=10,column=10,columnspan=2,sticky=W+E+N+S)


root.mainloop()